name: afri_parli_watch
description: "AfriParliWatch - Parliamentary Monitoring Platform"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  onesignal_flutter: ^5.1.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
